BL-1052-bd-design-development-plan
BloomTech-Labs/coder-heroes-docs pull request #15
Opened 2022-11-11 19:18 UTC by danielclark00

## Description

___Add your PR description here, deleting this example___

#### Video Link

[Loom Video](Add your loom video link here)

#### Trello Link

___Paste your trello card link here, deleting this example___

(Example below):

<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;JfipwNkb&#x2F;265-fix-refactor-sidebar-to-have-icons-representing-each-element-in-the-sidebar">Fix: Refactor sidebar to have icons representing each element in the sidebar</a></blockquote>

## Checklist:

- [ ] My design/diagram follows the style guidelines of this project
- [ ] My docs are organized within an appropriate folder structure in our repo
- [ ] Pull request description clearly describes docs made & motivations for said additions

2022-11-17 22:31 UTC, sarahlineb reviewed
very organized, easy to read, helpful links and information

2022-11-17 22:41 UTC, razborovdb approved these changes, later dismissed
The database schema, endpoints, and Jira ticket suggestions cover endpoints for creating the java backend application.

2022-11-18 06:02 UTC, deepalisethia commented on backend_design_doc.md
> +| [GET]  | /user/inbox/     | Returns an event object                                                     |
Maybe add periods at the end of the sentences on line 33 and 34 to keep with the pattern.

2022-11-18 06:03 UTC, deepalisethia commented on backend_design_doc.md
> +| [PUT]    | /children/{child_id}                               | Returns the updated child object                                                   |
periods on 79 and 80 as well

2022-11-18 06:03 UTC, deepalisethia commented on backend_design_doc.md
> +| [POST]   | /instructor/register               | Registers an instructor with data                                                                     |
periods on 105, 106

2022-11-18 06:04 UTC, deepalisethia commented on backend_design_doc.md
> +| [GET]    | /course             | Returns an array containing all course objects                                                                                         |
periods on 153, 157

2022-11-18 06:04 UTC, deepalisethia commented on backend_design_doc.md
> +| [PUT]    | /newsfeed/{newsfeed_id}  | Updates the newsfeed object with the given newsfeed_id and returns the newly updated newsfeed |
period

2022-11-18 06:05 UTC, deepalisethia commented on backend_design_doc.md
> +| [GET]    | /conversation_id/{profile_id} | Retrieves an inbox with the specified inbox_id                                                                                   |
period

2022-11-18 06:05 UTC, deepalisethia commented on backend_design_doc.md
> +| [GET]    | /calendar-events/user/       | Retrieves calendar event objects with the profile_id of logged in user              |
period on 214, 215

2022-11-18 06:07 UTC, deepalisethia requested changes
I'm not sure if punctuation matters at all - but since it is a design document, I assume that it does. I would just review where I left comments. If it doesn't matter so much - then please ignore and it looks pretty good to me. Clear, concise and to the point.

2022-11-18 13:55 UTC, razborovdb approved these changes, later dismissed

2022-11-18 16:58 UTC, deepalisethia approved these changes, later dismissed
Looks good to me!

2022-11-18 21:43 UTC, sarahlineb approved these changes, later dismissed

2022-11-21 20:14 UTC, sarahlineb approved these changes
👍

2022-11-21 20:22 UTC, deepalisethia approved these changes
Looks good.

2022-11-21 21:45 UTC, razborovdb approved these changes

2022-11-22 17:06 UTC, Jwatk13 reviewed
Great layout and organization of the endpoints and ticket suggestions.

2022-11-22 18:06 UTC, enbytedev commented
It looks good! It's a judgement call, especially given how much things can still change, but perhaps consider specifying HTTP response codes, the response body, etc. and the conditions for each. Perhaps lay out the middleware on each route, for example a "must be logged in" middleware may save repetition. This way everybody is on the same page.

2022-11-22 18:08 UTC, enbytedev approved these changes
It looks good! Perhaps lay out the middleware on each route, for example a "must be logged in" middleware may save repetition. This way everybody is on the same page.

2022-11-22 20:38 UTC, tkozzer commented
> It looks good! Perhaps lay out the middleware on each route, for example a "must be logged in" middleware may save repetition. This way everybody is on the same page.

If I'm understanding you correctly, I think this will be solved by the AuthInterceptor. So when somebody tries to hit an endpoint the first step will be to check if they are authenticated with a valid JWT. Then once they pass that stage, they can't proceed to an endpoint until we check that they have the appropriate permissions/roles. So the interceptor will be used to either allow a request to move forward or to return a 403 error.

There is a debate on whether to use a filter or an interceptor for handling this though. More on this debate can be found [here](https://stackoverflow.com/questions/35856454/difference-between-interceptor-and-filter-in-spring-mvc)

2022-11-24 00:56 UTC, AlexiusThomas approved these changes
Code looks dry and good job!

2022-11-29 19:38 UTC, merged